version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker-symfony6-php8.2-nginx-postgresql-chrome-webdriver/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      # IMPORTANT NOTE:
      # server name "Docker" should be set in PhpStorm Settings -> PHP -> Servers -> Name = Docker
      # Host => 127.0.0.1 Port => 888 Debugger => Xdebug
      # Add checked => Use path mapping
      # Add absolute path on server in project files => /var/www
      # Follow instruction picture in this catalog -> PhpStorm-XdebugSettings.png
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm