version: "3.8"

services:
  php-fpm:
    container_name: php-fpm-${COMPOSE_PROJECT_NAME}
    build:
      context: ./../
      dockerfile: ./docker-symfony6-php8.2-nginx-postgresql-chrome-webdriver/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      # IMPORTANT NOTE:
      # server name "Docker" should be set in PhpStorm Settings -> PHP -> Servers -> Name = Docker
      # Host => 127.0.0.1 Port => 888 Debugger => Xdebug
      # Add checked => Use path mapping
      # Add absolute path on server in project files => /var/www
      # Follow instruction picture in this catalog -> PhpStorm-XdebugSettings.png
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - globalnetwork
    volumes:
      - ./../:/var/www/


  nginx:
    container_name: nginx-${COMPOSE_PROJECT_NAME}
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    networks:
      - globalnetwork
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  supervisor:
    container_name: supervisor-${COMPOSE_PROJECT_NAME}
    build:
      context: ./supervisor
    ports:
      - "9001:9001"
    networks:
      - globalnetwork
    volumes:
      - ./sockets/supervisor.sock:/var/run/supervisor.sock
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - nginx

  database:
    container_name: postrgres-${COMPOSE_PROJECT_NAME}
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - globalnetwork
    volumes:
      - database_data:/var/lib/postgresql/data:rw
#  postrgres:
#    container_name: postrgres-${COMPOSE_PROJECT_NAME}
#    build:
#      context: ./postgres
#    ports:
#      - ${POSTGRES_PORT}:5432
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - db_data:/var/lib/postgresql/data:rw

networks:
  globalnetwork:

volumes:
  db_data:
  database_data:
